/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          100: "#fff5c8",
          400: "#facc15",
          500: "#eab308",
          600: "#ca8a04",
          700: "#a16207",
          900: "#713f12",
        },
        bg: "var(--color-bg)",
        surface: "var(--color-surface)",
        "surface-raised": "var(--color-surface-raised)",
        "surface-strong": "var(--color-surface-strong)",
        "surface-strong-foreground": "var(--color-surface-strong-foreground)",
        header: "var(--color-header)",
        rail: "var(--color-rail)",
        border: "var(--color-border)",
        "border-strong": "var(--color-border-strong)",
        accent: "var(--color-accent)",
        "accent-hover": "var(--color-accent-hover)",
        "accent-soft": "var(--color-accent-soft)",
        "accent-strong": "var(--color-accent-strong)",
        "accent-emphasis": "var(--color-accent-emphasis)",
        "accent-foreground": "var(--color-accent-foreground)",
        "chip-active-bg": "var(--color-chip-active-bg)",
        "chip-active-border": "var(--color-chip-active-border)",
        "chip-active-text": "var(--color-chip-active-text)",
        "chip-inactive-border": "var(--color-chip-inactive-border)",
        "chip-inactive-text": "var(--color-chip-inactive-text)",
        "chip-hover-bg": "var(--color-chip-hover-bg)",
        "chip-hover-text": "var(--color-chip-hover-text)",
        "card-tag-bg": "var(--color-card-tag-bg)",
        "card-tag-border": "var(--color-card-tag-border)",
        "card-tag-text": "var(--color-card-tag-text)",
        "card-tag-hover-bg": "var(--color-card-tag-hover-bg)",
        "card-tag-hover-border": "var(--color-card-tag-hover-border)",
        "card-tag-hover-text": "var(--color-card-tag-hover-text)",
        "card-title": "var(--color-card-title)",
        "body-link": "var(--color-body-link)",
        inverse: "var(--color-text-inverse)",
        "success-soft": "var(--color-success-soft)",
        "success-border": "var(--color-success-border)",
        "success-fg": "var(--color-success-fg)",
        success: "var(--color-success)",
        "success-hover": "var(--color-success-hover)",
        "danger-soft": "var(--color-danger-soft)",
        "danger-border": "var(--color-danger-border)",
        "danger-fg": "var(--color-danger-fg)",
        overlay: "var(--color-overlay)",
        "overlay-hover": "var(--color-overlay-hover)",
        "overlay-strong": "var(--color-overlay-strong)",
        scrim: "var(--color-scrim)",
        "media-control": "var(--color-media-control)",
        "media-control-ring": "var(--color-media-control-ring)",
        // S9-F1: Pulse chip tokens — avoids raw amber-* in component code
        "pulse-chip-bg": "var(--color-pulse-chip-bg)",
        "pulse-chip-fg": "var(--color-pulse-chip-fg)",
      },
      textColor: {
        primary: "var(--color-text-primary)",
        muted: "var(--color-text-muted)",
      },
      borderColor: {
        DEFAULT: "var(--color-border)",
      },
      ringColor: {
        focus: "var(--color-focus-ring)",
        elevated: "var(--color-elevated-ring)",
      },
      boxShadow: {
        panel: "var(--shadow-panel)",
        "chip-active": "var(--shadow-chip-active)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
